fix(Error: Property 'className' does not exist on type 'IntrinsicAttributes'. )
FIXED

ERROR in src/components/Header/Header.tsx:47:13
TS2322: Type '{ className: string; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'className' does not exist on type 'IntrinsicAttributes'.